<?php

use PHPUnit\Framework\TestCase;

class ParentTest extends TestCase
{
    /**
     * Test : Créer un parent avec un nom et un email valides
     */
    public function testCreateParentWithValidNameAndEmail()
    {
        // ARRANGE
        $name = "Jean Dupont";
        $email = "jean@example.com";
        
        // ACT
        $parent = new ParentUser($name, $email);
        
        // ASSERT
        $this->assertEquals($name, $parent->getName());
        $this->assertEquals($email, $parent->getEmail());
    }

    /**
     * Test : Vérifier que l'ID est généré automatiquement
     */
    public function testParentHasAutoGeneratedId()
    {
        // ACT
        $parent = new ParentUser("Marie Martin", "marie@example.com");
        
        // ASSERT
        $this->assertNotNull($parent->getId());
        $this->assertIsString($parent->getId());
        $this->assertNotEmpty($parent->getId());
    }

    /**
     * Test : Ne pas créer un parent avec un nom vide
     */
    public function testCannotCreateParentWithEmptyName()
    {
        // ASSERT
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage("Le nom ne peut pas être vide");
        
        // ACT
        new ParentUser("", "test@example.com");
    }

    /**
     * Test : Ne pas créer un parent avec un email vide
     */
    public function testCannotCreateParentWithEmptyEmail()
    {
        // ASSERT
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage("L'email ne peut pas être vide");
        
        // ACT
        new ParentUser("Pierre", "");
    }

    /**
     * Test : Ne pas créer un parent avec un email invalide
     */
    public function testCannotCreateParentWithInvalidEmail()
    {
        // ASSERT
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage("L'email n'est pas valide");
        
        // ACT
        new ParentUser("Sophie", "invalid-email");
    }

    /**
     * Test : Vérifier que la date de création est définie
     */
    public function testParentHasCreationDate()
    {
        // ACT
        $parent = new ParentUser("Luc", "luc@example.com");
        
        // ASSERT
        $this->assertInstanceOf(DateTime::class, $parent->getCreatedAt());
    }

    /**
     * Test : Vérifier que deux parents ont des IDs différents
     */
    public function testTwoParentsHaveDifferentIds()
    {
        // ACT
        $parent1 = new ParentUser("Anne", "anne@example.com");
        $parent2 = new ParentUser("Paul", "paul@example.com");
        
        // ASSERT
        $this->assertNotEquals($parent1->getId(), $parent2->getId());
    }

    /**
     * Test : Ajouter un adolescent à gérer
     */
    public function testCanAddManagedTeen()
    {
        // ARRANGE
        $parent = new ParentUser("Claire", "claire@example.com");
        $teen = new Teen("Alice", "alice@example.com", 15);
        
        // ACT
        $parent->addManagedTeen($teen);
        
        // ASSERT
        $this->assertCount(1, $parent->getManagedTeens());
        $this->assertContains($teen, $parent->getManagedTeens());
    }

    /**
     * Test : Ajouter plusieurs adolescents à gérer
     */
    public function testCanAddMultipleManagedTeens()
    {
        // ARRANGE
        $parent = new ParentUser("Thomas", "thomas@example.com");
        $teen1 = new Teen("Bob", "bob@example.com", 14);
        $teen2 = new Teen("Emma", "emma@example.com", 16);
        
        // ACT
        $parent->addManagedTeen($teen1);
        $parent->addManagedTeen($teen2);
        
        // ASSERT
        $this->assertCount(2, $parent->getManagedTeens());
    }

    /**
     * Test : Ne pas ajouter le même adolescent deux fois
     */
    public function testCannotAddSameTeenTwice()
    {
        // ARRANGE
        $parent = new ParentUser("Julie", "julie@example.com");
        $teen = new Teen("Charlie", "charlie@example.com", 13);
        
        // ACT
        $parent->addManagedTeen($teen);
        
        // ASSERT
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage("Cet adolescent est déjà géré");
        
        $parent->addManagedTeen($teen);
    }

    /**
     * Test : Retirer un adolescent géré
     */
    public function testCanRemoveManagedTeen()
    {
        // ARRANGE
        $parent = new ParentUser("Marc", "marc@example.com");
        $teen = new Teen("David", "david@example.com", 17);
        $parent->addManagedTeen($teen);
        
        // ACT
        $parent->removeManagedTeen($teen);
        
        // ASSERT
        $this->assertCount(0, $parent->getManagedTeens());
    }

    /**
     * Test : Ne pas retirer un adolescent qui n'est pas géré
     */
    public function testCannotRemoveTeenNotManaged()
    {
        // ARRANGE
        $parent = new ParentUser("Sylvie", "sylvie@example.com");
        $teen = new Teen("Eve", "eve@example.com", 12);
        
        // ASSERT
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage("Cet adolescent n'est pas géré par ce parent");
        
        // ACT
        $parent->removeManagedTeen($teen);
    }

    /**
     * Test : La liste des adolescents gérés est vide par défaut
     */
    public function testManagedTeensIsEmptyByDefault()
    {
        // ACT
        $parent = new ParentUser("Olivier", "olivier@example.com");
        
        // ASSERT
        $this->assertIsArray($parent->getManagedTeens());
        $this->assertCount(0, $parent->getManagedTeens());
    }

    /**
     * Test : Définir et récupérer le numéro de téléphone
     */
    public function testCanSetAndGetPhoneNumber()
    {
        // ARRANGE
        $parent = new ParentUser("Nathalie", "nathalie@example.com");
        $phone = "+33612345678";
        
        // ACT
        $parent->setPhoneNumber($phone);
        
        // ASSERT
        $this->assertEquals($phone, $parent->getPhoneNumber());
    }

    /**
     * Test : Le numéro de téléphone est null par défaut
     */
    public function testPhoneNumberIsNullByDefault()
    {
        // ACT
        $parent = new ParentUser("François", "francois@example.com");
        
        // ASSERT
        $this->assertNull($parent->getPhoneNumber());
    }
}
