<?php

use PHPUnit\Framework\TestCase;

class TeenTest extends TestCase
{
    /**
     * Test : Créer un adolescent avec un nom et un âge valides
     */
    public function testCreateTeenWithValidNameAndAge()
    {
        // ARRANGE
        $name = "Alice Dupont";
        $email = "alice@example.com";
        $age = 15;
        
        // ACT
        $teen = new Teen($name, $email, $age);
        
        // ASSERT
        $this->assertEquals($name, $teen->getName());
        $this->assertEquals($email, $teen->getEmail());
        $this->assertEquals($age, $teen->getAge());
    }

    /**
     * Test : Vérifier que l'ID est généré automatiquement
     */
    public function testTeenHasAutoGeneratedId()
    {
        // ACT
        $teen = new Teen("Bob Martin", "bob@example.com", 14);
        
        // ASSERT
        $this->assertNotNull($teen->getId());
        $this->assertIsString($teen->getId());
        $this->assertNotEmpty($teen->getId());
    }

    /**
     * Test : Ne pas créer un adolescent avec un âge négatif
     */
    public function testCannotCreateTeenWithNegativeAge()
    {
        // ASSERT
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage("L'âge doit être positif");
        
        // ACT
        new Teen("Charlie", "charlie@example.com", -5);
    }

    /**
     * Test : Ne pas créer un adolescent avec un âge de 0
     */
    public function testCannotCreateTeenWithZeroAge()
    {
        // ASSERT
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage("L'âge doit être positif");
        
        // ACT
        new Teen("David", "david@example.com", 0);
    }

    /**
     * Test : Ne pas créer un adolescent avec un âge supérieur à 18 ans
     */
    public function testCannotCreateTeenWithAgeAbove18()
    {
        // ASSERT
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage("L'âge doit être inférieur à 18 ans");
        
        // ACT
        new Teen("Eve", "eve@example.com", 19);
    }

    /**
     * Test : Accepter un adolescent de 18 ans exactement
     */
    public function testCanCreateTeenWithAge18()
    {
        // ACT
        $teen = new Teen("Frank", "frank@example.com", 18);
        
        // ASSERT
        $this->assertEquals(18, $teen->getAge());
    }

    /**
     * Test : Ne pas créer un adolescent sans nom
     */
    public function testCannotCreateTeenWithEmptyName()
    {
        // ASSERT
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage("Le nom ne peut pas être vide");
        
        // ACT
        new Teen("", "test@example.com", 15);
    }

    /**
     * Test : Ne pas créer un adolescent sans email
     */
    public function testCannotCreateTeenWithEmptyEmail()
    {
        // ASSERT
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage("L'email ne peut pas être vide");
        
        // ACT
        new Teen("Grace", "", 15);
    }

    /**
     * Test : Ne pas créer un adolescent avec un email invalide
     */
    public function testCannotCreateTeenWithInvalidEmail()
    {
        // ASSERT
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage("L'email n'est pas valide");
        
        // ACT
        new Teen("Henry", "invalid-email", 15);
    }

    /**
     * Test : Vérifier que la date de création est définie
     */
    public function testTeenHasCreationDate()
    {
        // ACT
        $teen = new Teen("Iris", "iris@example.com", 16);
        
        // ASSERT
        $this->assertInstanceOf(DateTime::class, $teen->getCreatedAt());
    }

    /**
     * Test : Modifier l'âge d'un adolescent
     */
    public function testCanUpdateTeenAge()
    {
        // ARRANGE
        $teen = new Teen("Jack", "jack@example.com", 14);
        
        // ACT
        $teen->setAge(15);
        
        // ASSERT
        $this->assertEquals(15, $teen->getAge());
    }

    /**
     * Test : Ne pas modifier l'âge avec une valeur invalide
     */
    public function testCannotUpdateTeenAgeWithInvalidValue()
    {
        // ARRANGE
        $teen = new Teen("Kate", "kate@example.com", 14);
        
        // ASSERT
        $this->expectException(InvalidArgumentException::class);
        $this->expectExceptionMessage("L'âge doit être positif");
        
        // ACT
        $teen->setAge(-1);
    }

    /**
     * Test : Vérifier que deux adolescents ont des IDs différents
     */
    public function testTwoTeensHaveDifferentIds()
    {
        // ACT
        $teen1 = new Teen("Leo", "leo@example.com", 13);
        $teen2 = new Teen("Mia", "mia@example.com", 14);
        
        // ASSERT
        $this->assertNotEquals($teen1->getId(), $teen2->getId());
    }

    /**
     * Test : Définir et récupérer l'école d'un adolescent
     */
    public function testCanSetAndGetSchool()
    {
        // ARRANGE
        $teen = new Teen("Nina", "nina@example.com", 15);
        $school = "Lycée Victor Hugo";
        
        // ACT
        $teen->setSchool($school);
        
        // ASSERT
        $this->assertEquals($school, $teen->getSchool());
    }

    /**
     * Test : L'école est null par défaut
     */
    public function testSchoolIsNullByDefault()
    {
        // ACT
        $teen = new Teen("Oscar", "oscar@example.com", 16);
        
        // ASSERT
        $this->assertNull($teen->getSchool());
    }
}
